version: '3.8'

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.8-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - default

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 177.16.57.0/24