summary: Detail
operationId: show-role-by-id
description: Info for a specific role
tags:
  - roles
parameters:
  - $ref: "../../common/parameters/path/id.yaml"
responses:
  200:
    description: Expected response to a valid request
    content:
      application/json:
        schema:
          $ref: "../../schemas/role.yaml"
  default:
    $ref: "../../common/responses/unexpected-error.yaml"